version: '3'
services:
        discovery-server:
                image: discovery-server
                ports:
                        - 8761:8761
        ratings-data-service:
                image: ratings-data-service
                ports:
                        - 8083:8083   
        movie-info-service:
                image: movie-info-service
                ports:
                        - 8082:8082
        movie-catalog-service:
                image: movie-catalog-service
                ports: 
                        - 8081:8081
                network_mode: host
